version: "3.9"
services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_APP_URL: "http://pulchri.daymeijroos.nl"
        NEXT_PUBLIC_APP_PORT: "80"
        NEXTAUTH_URL: "http://pulchri.daymeijroos.nl"
    working_dir: /app
    ports:
      - "3000:80"
    image: t3-app
    environment:
      - DATABASE_URL=database_url_goes_here
