version: "3.9"
services:
  nextjs:
    platform: "linux/arm64/v8"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=mysql://root:gsd7jewg79hdadsa@db:3306/pulchriplanner
    working_dir: /app
    ports:
      - "3000:3000"
    image: t3-app
    restart: unless-stopped
  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: 'pulchri.daymeijroos.nl'
      SITES: 'pulchri.daymeijroos.nl=nextjs:3000'
      FORCE_HTTPS: 'true'
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: gsd7jewg79hdadsa
      MYSQL_DATABASE: pulchriplanner
    volumes:
      - my-db:/var/lib/mysql

volumes:
  ssl_data:
  my-db:
